[project]
name = "cmaketomokai"
cpp_version = "c++23"

[target.cmaketomokai]
type = "executable"
sources = ["src/**/*.cxx"]
include_dirs = ["src/transpiler", "src/lib", "src/parser_api", "interface.hxx"]
