#pragma once

#include <filesystem>
#include <fstream>
#include <set>
#include <string>

namespace fs = std::filesystem;

namespace cmake_api::patchgen {

class PatchGen {
private:
  fs::path patchDir;

public:
  explicit PatchGen(const fs::path &buildDir)
      : patchDir(buildDir / ".mokai_parser_patch") {
    fs::create_directories(patchDir);
  }

  const fs::path &directory() const { return patchDir; }

  //------------------------------------------------------------------
  // Generates one file containing ALL imported targets.
  //------------------------------------------------------------------
  void generateTargets(const std::set<std::string> &importedTargets) {
    std::ofstream out(patchDir / "mokai_targets.cmake");

    out << "# Generated by Mokai\n\n";

    for (const auto &target : importedTargets) {
      out << "if(NOT TARGET " << target << ")\n"
          << "    add_library(" << target << " INTERFACE IMPORTED GLOBAL)\n"
          << "endif()\n\n";
    }
  }

  //------------------------------------------------------------------
  // Generates FindXXX.cmake files.
  //------------------------------------------------------------------
  void generateFindModule(const std::string &pkg) {
    std::ofstream out(patchDir / ("Find" + pkg + ".cmake"));

    out << "# Generated by Mokai\n\n"

        << "set(" << pkg << "_FOUND TRUE)\n"

        << "string(TOUPPER \"" << pkg << "\" _PKG)\n"
        << "set(${_PKG}_FOUND TRUE)\n\n"

        << "include(\"${CMAKE_CURRENT_LIST_DIR}/mokai_targets.cmake\")\n\n"

        << "if(NOT TARGET " << pkg << ")\n"
        << "    add_library(" << pkg << " INTERFACE IMPORTED GLOBAL)\n"
        << "endif()\n\n"

        << "if(NOT TARGET " << pkg << "::" << pkg << ")\n"
        << "    add_library(" << pkg << "::" << pkg
        << " INTERFACE IMPORTED GLOBAL)\n"
        << "endif()\n";
  }

  //------------------------------------------------------------------
  // Generates all FindXXX modules.
  //------------------------------------------------------------------
  void generateFindModules(const std::set<std::string> &packages) {
    for (const auto &p : packages)
      generateFindModule(p);
  }

  //------------------------------------------------------------------
  // Generates preload script.
  //------------------------------------------------------------------
  void generatePreload() {
    std::ofstream out(patchDir / "mokai_preload.cmake");

    out <<
        R"(# Generated by Mokai

set(MOKAI_PARSE_ONLY ON)

list(PREPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}")

include("${CMAKE_CURRENT_LIST_DIR}/mokai_targets.cmake")

#
# Disable FetchContent completely.
#

macro(FetchContent_Declare)
endmacro()

macro(FetchContent_MakeAvailable)
    message(STATUS "[Mokai] Skipping FetchContent: ${ARGV}")
endmacro()

macro(FetchContent_Populate)
endmacro()
)";
  }

  //------------------------------------------------------------------
  // Generate everything.
  //------------------------------------------------------------------
  void generate(const std::set<std::string> &packages,
                const std::set<std::string> &importedTargets) {
    generateTargets(importedTargets);
    generateFindModules(packages);
    generatePreload();
  }
};

} // namespace cmake_api::patchgen
