#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <string>

#include "codemodel/codemodel_parser.hxx"
#include "codemodel/idx_parser.hxx"
#include "interface.hxx"
#include "prepare/patch_gen.hxx"
#include "prepare/patcher.hxx"
#include "prepare/prescan.hxx"
#include "target/target_transpiler.hxx"
#include "utils/logger.hxx"

namespace fs = std::filesystem;

using namespace cmake_api::codemodel;
using namespace cmake_api::target;
using namespace cmake_api::patcher;

namespace cmake_api::entry {

class ApiParser : public IParser {
private:
  // fs::path targetPath;
  // fs::path outputPath;
  fs::path targetBuildDir;
  fs::path replyDir;

public:
  ApiParser(int argc, char *argv[]) {

    targetPath = argv[1];
    targetBuildDir = targetPath / "build";
    replyDir = targetBuildDir / ".cmake/api/v1/reply";
  }

  void generateCMakeApiQuery(const fs::path &targetBuildDir) {
    fs::path queryDir = targetBuildDir / ".cmake/api/v1/query/client-mokai";
    fs::create_directories(queryDir);

    std::ofstream queryFile(queryDir / "query.json");
    queryFile << R"({ "requests": [ { "kind": "codemodel", "version": 2 } ] })";
  }

  int run() override {
    logger::Logger::info("Parsing using CMake API", "cmake api");

    // 1. Setup API hooks natively
    logger::Logger::log("Injecting generation hooks...");
    generateCMakeApiQuery(targetBuildDir);

    // 2. Drive the generation phase to build the JSON IR
    logger::Logger::log("Running CMake intercept phase...");

    // ----------------------------
    // PHASE 1: SCAN
    // ----------------------------
    cmake_api::prescan::PreScanner scanner;

    for (auto &p : fs::recursive_directory_iterator(targetPath)) {
      if (p.path().extension() == ".txt" ||
          p.path().filename() == "CMakeLists.txt" ||
          p.path().extension() == ".cmake") {
        scanner.scanFile(p.path());
      }
    }

    logger::Logger::log("Found packages: " +
                        std::to_string(scanner.packages.size()));

    // ----------------------------
    // PHASE 2: PATCH GEN
    // ----------------------------
    cmake_api::patchgen::PatchGen patch(targetPath);

    // for (auto const &pkg : scanner.packages) {
    //   patch.generate(pkg, targetBuildDir / ".mokai_parser_patch");
    // }

    patch.generate(scanner.packages, scanner.importedTargets);

    // std::vector<std::string> flags;
    // patch.generateDisableFlags(scanner.packages, flags);

    // ----------------------------
    // PHASE 3: RUN CMAKE
    // ----------------------------

    std::string patchDir = (targetBuildDir / ".mokai_parser_patch").string();

    std::string cmd = "cmake -S " + targetPath.string() + " -B " +
                      targetBuildDir.string() +

                      // IMPORTANT: force module override first
                      " -DCMAKE_MODULE_PATH=" + patchDir +

                      // preload script hook
                      " -DCMAKE_PROJECT_TOP_LEVEL_INCLUDES=" + patchDir +
                      "/mokai_preload.cmake" +

                      // DO NOT disable fetchcontent globally
                      " -DFETCHCONTENT_FULLY_DISCONNECTED=OFF" +

                      " -DMOKAI_PARSE_ONLY=ON"
                      " > /dev/null 2>&1";

    int ret = std::system(cmd.c_str());

    if (ret != 0) {
      logger::Logger::error("CMake configuration failed.");
      logger::Logger::tip("Make sure the project correctly builds with CMake");
      return ret;
    }

    // INFO: Patch the CMake file first
    // CMakePatcher patcher(targetPath);
    // NATIVE PASS 1: Clean C++ Pre-processing injection step
    // logger::Logger::log("Pre-processing configuration workspace targets...");
    // patcher.patchFile(targetPath / fs::path("CMakeLists.txt"));
    // logger::Logger::log("Injection secured across " +
    //                     std::to_string(patcher.getPatchedCount()) +
    //                     " blueprint nodes.");

    try {
      std::string codemodelFile = IndexParser::extractCodemodel(replyDir);
      ProjectMetadata projectGraph =
          CodemodelParser::resolveProjectGraph(replyDir / codemodelFile);

      // Open structural file stream target definition
      std::ofstream mokaiManifest(targetPath / "mokai.toml");

      // Emit Configuration Header Block Natively
      mokaiManifest
          << "# "
             "================================================================="
             "======\n"
          << "# GENERATED BY MOKAI BUILD ENGINE COMPILER PASSTHROUGH\n"
          << "# "
             "================================================================="
             "======\n\n"
          << "[project]\n"
          << "name = \"" << projectGraph.projectName << "\"\n";

      // Evaluate target compilation configurations sequentially
      for (const auto &[name, blueprintPath] : projectGraph.targets) {
        // TargetTranspiler::transpile(replyDir / blueprintPath,
        //                             std::cout); // Output to stdout
        TargetTranspiler::transpile(replyDir / blueprintPath,
                                    mokaiManifest); // Commit directly to file
      }

      logger::Logger::success("Generated manifest with CMake API");
    } catch (const std::exception &e) {
      logger::Logger::error(std::string(e.what()) + "\n");
      return 1;
    }

    return 0;
  }
};

} // namespace cmake_api::entry
