#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iostream>

#include "codemodel/codemodel_parser.hxx"
#include "codemodel/idx_parser.hxx"
#include "interface.hxx"
#include "target/target_transpiler.hxx"
#include "utils/logger.hxx"

namespace fs = std::filesystem;

using namespace cmake_api::codemodel;
using namespace cmake_api::target;

namespace cmake_api::entry {

class ApiParser : public IParser {
private:
  // fs::path targetPath;
  // fs::path outputPath;
  fs::path targetBuildDir;
  fs::path replyDir;

public:
  ApiParser(int argc, char *argv[]) {
    if (argc < 2) {
      std::cerr << "Usage: mokai <path_to_target_project>\n";
    }

    targetPath = argv[1];
    targetBuildDir = targetPath / "build";
    replyDir = targetBuildDir / ".cmake/api/v1/reply";
  }

  void generateCMakeApiQuery(const fs::path &targetBuildDir) {
    fs::path queryDir = targetBuildDir / ".cmake/api/v1/query/client-mokai";
    fs::create_directories(queryDir);

    std::ofstream queryFile(queryDir / "query.json");
    queryFile << R"({ "requests": [ { "kind": "codemodel", "version": 2 } ] })";
  }

  int run() override {
    logger::Logger::info("Parsing using CMake API");

    // 1. Setup API hooks natively
    logger::Logger::log("Injecting generation hooks...");
    generateCMakeApiQuery(targetBuildDir);

    // 2. Drive the generation phase to build the JSON IR
    logger::Logger::log("Running CMake intercept phase...");
    std::string cmakeCmd = "cmake -S " + targetPath.string() + " -B " +
                           targetBuildDir.string() + " > /dev/null 2>&1";
    int ret = std::system(cmakeCmd.c_str());
    if (ret != 0) {
      logger::Logger::error("CMake configuration failed.");
      logger::Logger::tip(
          " - Make sure the project correctly builds with CMake");
      return ret;
    }

    try {
      std::string codemodelFile = IndexParser::extractCodemodel(replyDir);
      ProjectMetadata projectGraph =
          CodemodelParser::resolveProjectGraph(replyDir / codemodelFile);

      // Open structural file stream target definition
      std::ofstream mokaiManifest(targetPath / "mokai.toml");

      // Emit Configuration Header Block Natively
      mokaiManifest
          << "# "
             "================================================================="
             "======\n"
          << "# GENERATED BY MOKAI BUILD ENGINE COMPILER PASSTHROUGH\n"
          << "# "
             "================================================================="
             "======\n\n"
          << "[project]\n"
          << "name = \"" << projectGraph.projectName << "\"\n";

      // Evaluate target compilation configurations sequentially
      for (const auto &[name, blueprintPath] : projectGraph.targets) {
        // TargetTranspiler::transpile(replyDir / blueprintPath,
        //                             std::cout); // Output to stdout
        TargetTranspiler::transpile(replyDir / blueprintPath,
                                    mokaiManifest); // Commit directly to file
      }

      logger::Logger::success("Generated manifest with CMake API");
    } catch (const std::exception &e) {
      logger::Logger::error(std::string(e.what()) + "\n");
      return 1;
    }

    return 0;
  }
};

} // namespace cmake_api::entry
